"""buat table voucher

Revision ID: 239c311680dc
Revises: 49b943a33679
Create Date: 2024-09-17 17:02:34.940196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239c311680dc'
down_revision = '49b943a33679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher')
    # ### end Alembic commands ###
