"""Added NewTable

Revision ID: 8c6901f56395
Revises: 98b3fb587962
Create Date: 2024-11-18 01:34:01.671297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6901f56395'
down_revision = '98b3fb587962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record__redemption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('total_redeemed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record__redemption')
    # ### end Alembic commands ###
